const defaultFilters = {
    filters: [
        {
            name: "Chromatic Aberration",
            "xml":"<xml xmlns=\"https://developers.google.com/blockly/xml\"><variables><variable id=\"0argu%+[aZPsLM+)t:}(\">pixel</variable></variables><block type=\"for_each_pixel\" id=\"{~CbTV}~[Q42e2ADFK}Q\" x=\"106\" y=\"163\"><field name=\"PIXEL_VAR\" id=\"0argu%+[aZPsLM+)t:}(\">pixel</field><statement name=\"Loop\"><block type=\"variables_set\" id=\"g`lwqhp),#j)mkeCF$t5\"><field name=\"VAR\" id=\"0argu%+[aZPsLM+)t:}(\">pixel</field><value name=\"VALUE\"><block type=\"colour_rgb\" id=\"Y$hS#9i`oc#E@e9#JsaU\"><value name=\"RED\"><block type=\"get_red_of\" id=\"-[w)1Wzy:1--Ll0)ilpD\"><value name=\"NAME\"><block type=\"get_pixel_relative\" id=\"!1G=(pH==UE_{PSBvzQ2\"><field name=\"X_VAL\">5</field><field name=\"Y_VAL\">5</field><value name=\"NAME\"><block type=\"variables_get\" id=\"39nZ]@u7~$^c6ZGsnBcc\"><field name=\"VAR\" id=\"0argu%+[aZPsLM+)t:}(\">pixel</field></block></value></block></value></block></value><value name=\"GREEN\"><block type=\"get_green_of\" id=\"(?usMY}6FuS6JugAhNO*\"><value name=\"NAME\"><block type=\"variables_get\" id=\"Jx7(^,QF;7o#)6|LWM1=\"><field name=\"VAR\" id=\"0argu%+[aZPsLM+)t:}(\">pixel</field></block></value></block></value><value name=\"BLUE\"><block type=\"get_blue_of\" id=\"1_UZ.L@5QYF]AY+ofL+b\"><value name=\"NAME\"><block type=\"variables_get\" id=\"WQ3X/qFMO2O!t^$~t,YI\"><field name=\"VAR\" id=\"0argu%+[aZPsLM+)t:}(\">pixel</field></block></value></block></value></block></value></block></statement></block></xml>"
        },
        {  
            name: "Grain",
            xml:"<xml xmlns=\"https://developers.google.com/blockly/xml\"><variables><variable id=\"0argu%+[aZPsLM+)t:}(\">pixel</variable></variables><block type=\"for_each_pixel\" id=\"{~CbTV}~[Q42e2ADFK}Q\" x=\"100\" y=\"115\"><field name=\"PIXEL_VAR\" id=\"0argu%+[aZPsLM+)t:}(\">pixel</field><statement name=\"Loop\"><block type=\"variables_set\" id=\"g`lwqhp),#j)mkeCF$t5\"><field name=\"VAR\" id=\"0argu%+[aZPsLM+)t:}(\">pixel</field><value name=\"VALUE\"><block type=\"colour_blend\" id=\"!1)Sro?i+EeB|/#CDGy9\"><value name=\"COLOUR1\"><shadow type=\"colour_picker\" id=\"5R@uqDTT$=tsLV-y-qSO\"><field name=\"COLOUR\">#ff0000</field></shadow><block type=\"colour_rgb\" id=\"Y$hS#9i`oc#E@e9#JsaU\"><value name=\"RED\"><block type=\"get_red_of\" id=\"-[w)1Wzy:1--Ll0)ilpD\"><value name=\"NAME\"><block type=\"variables_get\" id=\"39nZ]@u7~$^c6ZGsnBcc\"><field name=\"VAR\" id=\"0argu%+[aZPsLM+)t:}(\">pixel</field></block></value></block></value><value name=\"GREEN\"><block type=\"get_green_of\" id=\"(?usMY}6FuS6JugAhNO*\"><value name=\"NAME\"><block type=\"variables_get\" id=\"WQ3X/qFMO2O!t^$~t,YI\"><field name=\"VAR\" id=\"0argu%+[aZPsLM+)t:}(\">pixel</field></block></value></block></value><value name=\"BLUE\"><block type=\"get_blue_of\" id=\"1_UZ.L@5QYF]AY+ofL+b\"><value name=\"NAME\"><block type=\"variables_get\" id=\"Jx7(^,QF;7o#)6|LWM1=\"><field name=\"VAR\" id=\"0argu%+[aZPsLM+)t:}(\">pixel</field></block></value></block></value></block></value><value name=\"COLOUR2\"><shadow type=\"colour_picker\" id=\"d]I+,_:1Z*+rI#$C.-:f\"><field name=\"COLOUR\">#3333ff</field></shadow><block type=\"colour_random\" id=\"{.sR.{a#-JFN63[^[:D,\"></block></value><value name=\"RATIO\"><shadow type=\"math_number\" id=\"iTZ65H3f3-yzL`wN8:]4\"><field name=\"NUM\">0.2</field></shadow></value></block></value></block></statement></block></xml>",
        }
    ]
}

export default defaultFilters;
